-- MySQL Script generated by MySQL Workbench
-- Sun Sep 17 21:18:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db-capstone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db-capstone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db-capstone` DEFAULT CHARACTER SET utf8 ;
USE `db-capstone` ;

-- -----------------------------------------------------
-- Table `db-capstone`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-capstone`.`Customers` (
  `idCustomers` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `contact` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NULL,
  PRIMARY KEY (`idCustomers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-capstone`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-capstone`.`Orders` (
  `idOrders` INT NOT NULL,
  `date` DATE NULL,
  `quantity` INT NULL,
  `totalcost` VARCHAR(45) NULL,
  PRIMARY KEY (`idOrders`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-capstone`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-capstone`.`Staff` (
  `idStaff` INT NOT NULL,
  `role` VARCHAR(45) NULL,
  `salary` VARCHAR(45) NULL,
  PRIMARY KEY (`idStaff`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-capstone`.`Bookins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-capstone`.`Bookins` (
  `idBookins` INT NOT NULL,
  `date` DATE NULL,
  `tableNumber` INT NULL,
  `Customers_idCustomers` INT NOT NULL,
  `Orders_idOrders` INT NOT NULL,
  `Staff_idStaff` INT NOT NULL,
  PRIMARY KEY (`idBookins`, `Orders_idOrders`),
  INDEX `fk_Bookins_Customers1_idx` (`Customers_idCustomers` ASC) VISIBLE,
  INDEX `fk_Bookins_Orders1_idx` (`Orders_idOrders` ASC) VISIBLE,
  INDEX `fk_Bookins_Staff1_idx` (`Staff_idStaff` ASC) VISIBLE,
  CONSTRAINT `fk_Bookins_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `db-capstone`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bookins_Orders1`
    FOREIGN KEY (`Orders_idOrders`)
    REFERENCES `db-capstone`.`Orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bookins_Staff1`
    FOREIGN KEY (`Staff_idStaff`)
    REFERENCES `db-capstone`.`Staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-capstone`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-capstone`.`Menu` (
  `idMenu` INT NOT NULL,
  `cuisines` VARCHAR(45) NULL,
  `starters` VARCHAR(45) NULL,
  `courses` VARCHAR(45) NULL,
  `drinks` VARCHAR(45) NULL,
  `Menucol` VARCHAR(45) NULL,
  PRIMARY KEY (`idMenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-capstone`.`Orders_has_Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-capstone`.`Orders_has_Menu` (
  `Orders_idOrders` INT NOT NULL,
  `Menu_idMenu` INT NOT NULL,
  PRIMARY KEY (`Orders_idOrders`, `Menu_idMenu`),
  INDEX `fk_Orders_has_Menu_Menu1_idx` (`Menu_idMenu` ASC) VISIBLE,
  INDEX `fk_Orders_has_Menu_Orders1_idx` (`Orders_idOrders` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_has_Menu_Orders1`
    FOREIGN KEY (`Orders_idOrders`)
    REFERENCES `db-capstone`.`Orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_has_Menu_Menu1`
    FOREIGN KEY (`Menu_idMenu`)
    REFERENCES `db-capstone`.`Menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-capstone`.`Customers_has_Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-capstone`.`Customers_has_Orders` (
  `Customers_idCustomers` INT NOT NULL,
  `Orders_idOrders` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`Customers_idCustomers`, `Orders_idOrders`),
  INDEX `fk_Customers_has_Orders_Orders1_idx` (`Orders_idOrders` ASC) VISIBLE,
  INDEX `fk_Customers_has_Orders_Customers1_idx` (`Customers_idCustomers` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_has_Orders_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `db-capstone`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customers_has_Orders_Orders1`
    FOREIGN KEY (`Orders_idOrders`)
    REFERENCES `db-capstone`.`Orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
